### ISSUE TITLE
Clarification required for chbsp_i2c_mem_write()

### ISSUE THREAD

**Issue by mmurty** [tdk-invn-oss/ultrasonic.soniclib#13]
Hello,
I see that the documentation (comment) for the chbsp_i2c_mem_write() function mentions that we should send the following I2C sequence when the function is implemented:
 I2C Addr | \a mem_addr | \a num_bytes |  *\a data | *(\a data + 1)| *(\a data + 2)|   ...

but I don't see this sequence implemented in the arduino code [here](https://github.com/tdk-invn-oss/ultrasonic.arduino.CHx01/blob/main/src/board/chbsp_chirp.cpp) and I don't see it in the hello chirp example project for the SAM device either. 

Can you please clarify which one is correct documentation / code?

---
Notify: @tdk-invn-oss/ultrasonic-maintainers

**Comment by gferard-invn** [comment]
Hi @mmurty,
thanks for your remark. As you pointed it in the implementation's references, **the comment is the BSP header is wrong**, there is no need to send the number of bytes before the buffer.
